/**
 * Parity between the schema and the committed docs: .env.example and the README environment
 * section are generated by `pnpm docs:env`, and this suite fails the moment they drift (CI
 * also runs `pnpm docs:env --check`).
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  envSchema,
  README_ENV_END,
  README_ENV_START,
  renderEnvExample,
  renderReadmeSection,
  replaceBetween,
  type Catalogs,
} from '../../src/config/index.js';
import { llmCatalog } from '../../src/llm/registry.js';
import { presets } from '../../src/tools/registry.js';

const root = resolve(import.meta.dirname, '..', '..');
const catalogs: Catalogs = { llm: llmCatalog, automation: presets };
const { list } = envSchema(catalogs);
const visible = list.filter((s) => !s.hidden);

describe('generated environment docs', () => {
  const envExample = readFileSync(resolve(root, '.env.example'), 'utf8');
  const readme = readFileSync(resolve(root, 'README.md'), 'utf8');

  it('.env.example is what the schema renders (run pnpm docs:env after a schema change)', () => {
    expect(envExample).toBe(renderEnvExample(list));
  });

  it('the README section between the markers is what the schema renders', () => {
    expect(readme.indexOf(README_ENV_START)).toBeLessThan(readme.indexOf(README_ENV_END));
    expect(replaceBetween(readme, renderReadmeSection(list))).toBe(readme);
  });

  it('every documented variable appears in both files, in schema order', () => {
    let lastEnv = -1;
    let lastReadme = -1;
    for (const spec of visible) {
      const envMatch = new RegExp(`^#? ?${spec.key}=`, 'm').exec(envExample);
      expect(envMatch, `${spec.key} in .env.example`).not.toBeNull();
      expect(envMatch?.index ?? -1).toBeGreaterThan(lastEnv);
      lastEnv = envMatch?.index ?? -1;
      const readmeIndex = readme.indexOf(`| \`${spec.key}\``);
      expect(readmeIndex, `${spec.key} in README.md`).toBeGreaterThan(lastReadme);
      lastReadme = readmeIndex;
    }
    for (const spec of list.filter((s) => s.hidden)) {
      expect(envExample).not.toContain(spec.key);
      expect(readme).not.toContain(spec.key);
    }
  });

  it('.env.example is dotenv-shaped, leaves every secret blank and comments out what Railway sets', () => {
    for (const line of envExample.split('\n')) {
      if (line === '' || line.startsWith('#')) continue;
      expect(line).toMatch(/^[A-Z][A-Z0-9_]*=/);
    }
    for (const spec of visible.filter((s) => s.secret)) {
      expect(envExample).toMatch(new RegExp(`^${spec.key}=$`, 'm'));
    }
    for (const spec of visible.filter(
      (s) => s.setBy === 'railway' && s.defaultValue === undefined,
    )) {
      expect(envExample).toMatch(new RegExp(`^# ${spec.key}=$`, 'm'));
    }
    expect(envExample).toMatch(/^PORT=3000$/m);
    expect(envExample).toMatch(/^LLM_PROVIDER=openai$/m);
    expect(envExample).toMatch(/^AUTOMATION_PROVIDER=none$/m);
    expect(envExample).toMatch(/^# SYSTEM_PROMPT=$/m);
    expect(envExample).toMatch(/^FALLBACK_MESSAGE="Sorry, I am having trouble right now\./m);
  });

  it('lists the advertised providers and presets, never the fake provider', () => {
    const table = renderReadmeSection(list);
    expect(table).toContain('Values: openai, anthropic, google, mistral, groq.');
    expect(table).toContain('Values: none, make, zapier, n8n.');
    expect(table).not.toMatch(/\bfake\b/);
    expect(renderEnvExample(list)).not.toMatch(/\bfake\b/);
    for (const entry of llmCatalog.filter((e) => e.advertised && e.keyEnv !== null)) {
      expect(table).toContain(
        `| \`${entry.keyEnv ?? ''}\` (secret) | when LLM_PROVIDER is ${entry.id} |  | ${entry.keyDescription} |`,
      );
      expect(table).toContain(`${entry.id}: ${entry.defaultModel}`);
    }
    expect(table).toContain('| `WS_SECRET` (secret) | yes |  |');
    expect(table).toContain('| `RAILWAY_PUBLIC_DOMAIN` | set by Railway |  |');
    expect(table).toContain(
      '| `TWILIO_AUTH_TOKEN` (secret) | when TWILIO_SIGNATURE_MODE is enforce |  |',
    );
    expect(table).toContain('| `AUTOMATION_WEBHOOK_URL` | unless AUTOMATION_PROVIDER is none |  |');
  });

  it('replaceBetween keeps everything outside the markers and refuses a README without them', () => {
    const doc = `before\n${README_ENV_START}\nold\n${README_ENV_END}\nafter\n`;
    expect(replaceBetween(doc, 'new')).toBe(
      `before\n${README_ENV_START}\nnew\n${README_ENV_END}\nafter\n`,
    );
    expect(() => replaceBetween('no markers', 'x')).toThrow(/markers/);
  });
});
