/**
 * Renders .env.example and the README environment section from the schema. Pure functions:
 * scripts/docs-env.ts writes the files and checks them in CI; test/config/docs.test.ts asserts
 * that what is committed matches the schema.
 */
import type { EnvGroup, EnvSpec } from './types.js';

export const README_ENV_START = '<!-- env:start -->';
export const README_ENV_END = '<!-- env:end -->';

const GROUP_ORDER: readonly EnvGroup[] = [
  'Server',
  'Twilio and secrets',
  'LLM',
  'Prompt and spoken messages',
  'Automation',
  'Call limits',
  'Set by Railway',
];

function grouped(list: readonly EnvSpec[]): [EnvGroup, EnvSpec[]][] {
  const visible = list.filter((s) => !s.hidden);
  return GROUP_ORDER.map((group): [EnvGroup, EnvSpec[]] => [
    group,
    visible.filter((s) => s.group === group),
  ]).filter(([, specs]) => specs.length > 0);
}

/** Only Railway provides it; a deployer never sets it. */
const railwayOnly = (spec: EnvSpec): boolean =>
  spec.setBy === 'railway' && spec.defaultValue === undefined;

export function requiredText(spec: EnvSpec): string {
  if (railwayOnly(spec)) return 'set by Railway';
  if (spec.required === true) return 'yes';
  if (spec.required === false) return 'no';
  return spec.requiredNote ?? 'sometimes';
}

/** The default as the deployer would type it, or '' when there is none or it is described by defaultDoc. */
export function defaultLiteral(spec: EnvSpec): string {
  if (spec.defaultDoc !== undefined) return '';
  if (spec.defaultText !== undefined) return spec.defaultText;
  const v = spec.defaultValue;
  if (typeof v === 'string') return v;
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  return '';
}

const valuesNote = (spec: EnvSpec): string =>
  spec.validValues && spec.validValues.length > 0 ? ` Values: ${spec.validValues.join(', ')}.` : '';

const quoteForDotenv = (value: string): string =>
  /[\s#"'$]/.test(value) ? `"${value.replace(/"/g, '\\"')}"` : value;

function envLine(spec: EnvSpec): string {
  if (railwayOnly(spec) || spec.defaultDoc !== undefined) return `# ${spec.key}=`;
  if (spec.secret) return `${spec.key}=`;
  return `${spec.key}=${quoteForDotenv(defaultLiteral(spec))}`;
}

/** Ends the text with one period, whether or not it already had one. */
const sentence = (text: string): string => (/[.!?]$/.test(text) ? text : `${text}.`);

function flagsLine(spec: EnvSpec): string {
  const parts = [sentence(`Required: ${requiredText(spec)}`)];
  const literal = defaultLiteral(spec);
  if (spec.defaultDoc !== undefined) parts.push(sentence(`Default: ${spec.defaultDoc}`));
  else if (literal !== '') parts.push(sentence(`Default: ${literal}`));
  if (spec.secret) parts.push('Secret.');
  return `# ${parts.join(' ')}`;
}

export function renderEnvExample(list: readonly EnvSpec[]): string {
  const lines = [
    '# voice-server environment variables.',
    '# Generated by `pnpm docs:env` from src/config/schema.ts. Do not edit by hand.',
    '# Local runs: copy to .env. Railway: set these as service variables.',
    '# Blank secrets are yours to fill in. A commented-out variable is optional or set by Railway.',
    '',
  ];
  for (const [group, specs] of grouped(list)) {
    lines.push(`# --- ${group} ---`, '');
    for (const spec of specs) {
      lines.push(`# ${spec.description}${valuesNote(spec)}`, flagsLine(spec), envLine(spec), '');
    }
  }
  return lines.join('\n');
}

const cell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');

function defaultCell(spec: EnvSpec): string {
  if (spec.defaultDoc !== undefined) return cell(spec.defaultDoc);
  const literal = defaultLiteral(spec);
  return literal === '' ? '' : `\`${cell(literal)}\``;
}

export function renderReadmeSection(list: readonly EnvSpec[]): string {
  const out: string[] = [];
  for (const [group, specs] of grouped(list)) {
    out.push(
      `### ${group}`,
      '',
      '| Variable | Required | Default | Description |',
      '| --- | --- | --- | --- |',
    );
    for (const spec of specs) {
      const variable = `\`${spec.key}\`${spec.secret ? ' (secret)' : ''}`;
      out.push(
        `| ${variable} | ${requiredText(spec)} | ${defaultCell(spec)} | ${cell(spec.description + valuesNote(spec))} |`,
      );
    }
    out.push('');
  }
  return out.join('\n').trimEnd();
}

/** Puts `body` between the README markers, keeping everything else byte for byte. */
export function replaceBetween(readme: string, body: string): string {
  const start = readme.indexOf(README_ENV_START);
  const end = readme.indexOf(README_ENV_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `README.md needs the markers ${README_ENV_START} and ${README_ENV_END}, in that order.`,
    );
  }
  return `${readme.slice(0, start + README_ENV_START.length)}\n${body}\n${readme.slice(end)}`;
}
